export type GuildSetting = {
  guildId: string;
  actingOwner: string | null;
  bumpNotice: boolean;
  bumpNoticeRole: string | null;
  bumpNoticeContent: string | null;
  inviteLinkBlock: boolean;
  logAntiRaid: string | null;
  logMemberJoin: string | null;
  logMemberLeave: string | null;
  logMemberTimeout: string | null;
  logMemberKick: string | null;
  logMemberBan: string | null;
  logMemberUnban: string | null;
  logRoleCreate: string | null;
  logRoleEdit: string | null;
  logRoleDelete: string | null;
  logChannelCreate: string | null;
  logChannelEdit: string | null;
  logChannelDelete: string | null;
  logMessageEdit: string | null;
  logMessageDelete: string | null;
  logVoiceJoin: string | null;
  logVoiceLeave: string | null;
  welcomeMessageChannel: string | null;
  welcomeMessageContent: string | null;
  leaveMessageChannel: string | null;
  leaveMessageContent: string | null;
  statChannelAllMembers: string | null;
  statChannelUsers: string | null;
  statChannelBots: string | null;
  statChannelActiveRate: string | null;
  statChannelActiveRateRanking: string | null;
  ttsDefaultSpeakerId: number | null;
  ttsSkipUrl: boolean;
  ttsSkipCodeBlock: boolean;
};

export type GuildSettingUpdateInput = Pick<GuildSetting, "guildId"> & Partial<GuildSetting>;

export type GuildSettingUpsertInput = Pick<GuildSetting, "guildId"> & Partial<GuildSetting>;
