FROM ubuntu:24.04

ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

ARG BUN_VERSION=1.3.13
ARG NODE_VERSION=24.18.0
ARG NPM_VERSION=11.17.0
ARG JQ_VERSION=1.8.1
ARG GITLEAKS_VERSION=8.30.1
ARG TRUFFLEHOG_VERSION=3.95.6
ARG PLAYWRIGHT_VERSION=1.60.0

SHELL ["/bin/bash", "-c"]

RUN apt-get update \
    && apt-get install -y \
    ca-certificates \
    curl \
    git \
    gnupg \
    golang \
    htop \
    nodejs \
    npm \
    postgresql-client \
    sudo \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN [[ $(id -u ubuntu) = $USER_UID ]] || usermod -u $USER_UID ubuntu \
    && [[ $(id -g ubuntu) = $USER_GID ]] || groupmod -g $USER_GID ubuntu \
    && echo "ubuntu ALL=NOPASSWD: ALL" > /etc/sudoers.d/ubuntu \
    && chmod 0440 /etc/sudoers.d/ubuntu

# Update node and npm version
RUN npm i -g n \
    && yes | n ${NODE_VERSION} \
    && apt purge -y nodejs npm

# Install npm packages
RUN npm i -g \
    bun@${BUN_VERSION} \
    npm@${NPM_VERSION} \
    playwright@${PLAYWRIGHT_VERSION}

# Install scanning secrets tools
RUN curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/v${TRUFFLEHOG_VERSION}/scripts/install.sh | sh -s -- -b /usr/local/bin
RUN git clone -b v${GITLEAKS_VERSION} --depth 1 https://github.com/gitleaks/gitleaks.git \
  && cd gitleaks \
  && make build
ENV PATH="${PATH}:/gitleaks"

RUN curl -o /usr/local/bin/jq -L https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 && chmod +x /usr/local/bin/jq

RUN playwright install --with-deps

USER ubuntu
