services:
  db:
    container_name: distopia-db
    image: postgres:17
    volumes:
      - distopia-db-store:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - distopia-network
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: "test"

  app:
    container_name: distopia-app
    depends_on:
      - db
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
    init: true
    networks:
      - distopia-network
    command: sleep infinity
    volumes:
      - ..:/workspaces/distopia:cached
      - distopia-cache:/workspaces/distopia/.cache
      - distopia-node-modules:/workspaces/distopia/node_modules

volumes:
  distopia-db-store:
    external: true
  distopia-cache:
  distopia-node-modules:

networks:
  distopia-network:
