services:
  db:
    container_name: distopia
    image: postgres:17
    volumes:
      - distopia-db-store:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: "test"

  app:
    depends_on:
      - db
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
    init: true
    command: sleep infinity
    volumes:
      - ..:/workspaces/distopia:cached

volumes:
  distopia-db-store:
