import type { AppState } from "app-core/AppState";
import {
  ButtonRateLimit,
  ChatInputCommandRateLimit,
  Friend,
  GuildBlackList,
  GuildBumpRateLimit,
  GuildDictionary,
  GuildEdit,
  GuildMemberAdd,
  GuildSetting,
  GuildTtsIgnoreList,
  GuildWhiteList,
  JWTKey,
  MessageCreate,
  MessageCreateRateLimit,
  OAuth2Guilds,
  OAuth2PKCE,
  UnJoinedGuild,
  UrlCacheInMemory,
  UserDictionary,
  UserJWTVerifyKey,
  UserOAuth2,
  VoiceChannelMember,
} from "repo-memory";

export const memory: AppState["memory"] = {
  ratelimit: {
    messageCreate: new MessageCreateRateLimit(),
    bump: new GuildBumpRateLimit(),
    button: new ButtonRateLimit(),
    chatInputCommand: new ChatInputCommandRateLimit(),
  },
  friend: new Friend(),
  guildBlackList: new GuildBlackList(),
  guildDictionary: new GuildDictionary(),
  guildEdit: new GuildEdit(),
  guildSetting: new GuildSetting(),
  guildTtsIgnoreList: new GuildTtsIgnoreList(),
  guildWhiteList: new GuildWhiteList(),
  guildMemberAdd: new GuildMemberAdd(),
  jwtKey: new JWTKey(),
  messageCreate: new MessageCreate(),
  oauth2PKCE: new OAuth2PKCE(),
  oauth2Guilds: new OAuth2Guilds(),
  unJoinedGuild: new UnJoinedGuild(),
  urlCacheInMemory: new UrlCacheInMemory(),
  userDictionary: new UserDictionary(),
  userJWTVerifyKey: new UserJWTVerifyKey(),
  userOAuth2: new UserOAuth2(),
  voiceChannelMember: new VoiceChannelMember(),
};
