import type { AppState } from "app-core/AppState";
import {
  ButtonLateLimit,
  ChatInputCommandLateLimit,
  Friend,
  GuildBumpLateLimit,
  GuildEdit,
  GuildMemberAdd,
  GuildSetting,
  GuildWhiteList,
  JWTKey,
  MessageCreate,
  MessageCreateLateLimit,
  OAuth2Guilds,
  OAuth2PKCE,
  UnJoinedGuild,
  UrlCacheInMemory,
  UserJWTVerifyKey,
  UserOAuth2,
  VoiceChannelMember,
} from "repo-memory";

export const memory: AppState["memory"] = {
  latelimit: {
    messageCreate: new MessageCreateLateLimit(),
    bump: new GuildBumpLateLimit(),
    button: new ButtonLateLimit(),
    chatInputCommand: new ChatInputCommandLateLimit(),
  },
  friend: new Friend(),
  guildEdit: new GuildEdit(),
  guildSetting: new GuildSetting(),
  guildWhiteList: new GuildWhiteList(),
  guildMemberAdd: new GuildMemberAdd(),
  jwtKey: new JWTKey(),
  messageCreate: new MessageCreate(),
  oauth2PKCE: new OAuth2PKCE(),
  oauth2Guilds: new OAuth2Guilds(),
  unJoinedGuild: new UnJoinedGuild(),
  urlCacheInMemory: new UrlCacheInMemory(),
  userJWTVerifyKey: new UserJWTVerifyKey(),
  userOAuth2: new UserOAuth2(),
  voiceChannelMember: new VoiceChannelMember(),
};
