name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: pr-preview-${{ github.event_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  PUBLIC_URL: http://localhost:3000
  PUBLIC_OWNER_ID: "1261634733037719593"

  PUBLIC_HOME_SERVER_ID: "1505540430110920764"
  PUBLIC_STAFF_ROLE_ID: "1505546268020310117"
  PUBLIC_HONORARY_MEMBER_ROLE_ID: "1505546306721026068"
  PUBLIC_SPECIAL_BOARD_OF_DIRECTORS_ROLE_ID: "1505546372726788126"
  PUBLIC_BOARD_OF_DIRECTORS_ROLE_ID: "1505546412484726804"
  PUBLIC_SUB_BOARD_OF_DIRECTORS_ROLE_ID: "1505546443392422010"

  PUBLIC_BOT_ID: "1505544379639660745"

  PAGE_DIR: pr-preview-${{ github.event.pull_request.number }}

jobs:
  build-storybook:
    name: build Storybook
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository) || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || '' }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.15.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build-storybook

      - name: Move
        run: |
          mkdir tmp
          mv src/presentation/web/storybook-static tmp/storybook-static

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: storybook-output
          path: tmp/storybook-static/
          retention-days: 1

  preview:
    name: Preview
    runs-on: ubuntu-latest
    needs: [build-storybook]
    if: >-
      github.event.action != 'closed' &&
      github.event_name != 'push' &&
      github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v7
        with:
          ref: gh-pages

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: storybook-output
          path: tmp/storybook-static/

      - name: Move
        run: |
          if [ -e "storybook/${{ env.PAGE_DIR }}" ]; then
            rm -rf storybook/${{ env.PAGE_DIR }}/*
          else
            mkdir -p storybook/${{ env.PAGE_DIR }}
          fi
          mv -f tmp/storybook-static/* storybook/${{ env.PAGE_DIR }}

      - name: Clean Dir
        run: |
          find . -maxdepth 1 -mindepth 1 \
          ! -name 'storybook' \
          ! -name '.git' \
          -exec rm -rf {} +

      - name: Create .nojekyll
        run: touch .nojekyll

      - name: Commit changes to gh-pages branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Deploy PR preview for #${{ github.event.pull_request.number }}"
          git push origin gh-pages

      - name: Comment PR
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview deployed to: https://${context.repo.owner}.github.io/distopia/storybook/${process.env.PAGE_DIR}`
            })

  cleanup:
    name: Cleanup preview
    if: >-
      github.event.action == 'closed' &&
      (
        (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository) ||
        (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v7
        with:
          ref: gh-pages

      - name: Remove preview directory
        run: |
          rm -rf storybook/${{ env.PAGE_DIR }} || exit 0
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
            git commit -m "Remove PR preview for #${{ github.event.pull_request.number }}" && git push origin gh-pages || echo "No changes to commit"
