name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  npm:
    name: npmjs.com
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build with GHA cache
        uses: docker/build-push-action@v7
        with:
            context: ./docker
            push: false
            load: true
            cache-from: type=gha
            cache-to: type=gha,mode=max

      - name: Checkout Container
        working-directory: ./docker/
        shell: bash
        run: |
          docker volume create distopia-db-store
          docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d

      - name: Publish
        working-directory: ./docker/
        run: |
          docker compose exec app sudo bun ci
#         docker compose exec app sudo bash -c "cd lib/distopia && sudo bun publish --tolerate-republish ${{ github.event_name == 'pull_request' && '--dry-run' || '' }}"

  jsr:
    name: jsr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build with GHA cache
        uses: docker/build-push-action@v7
        with:
            context: ./docker
            push: false
            load: true
            cache-from: type=gha
            cache-to: type=gha,mode=max

      - name: Checkout Container
        working-directory: ./docker/
        shell: bash
        run: |
          docker volume create distopia-db-store
          docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d

      - name: Install Deps
        run:  docker compose exec app sudo bun ci

      - name: Publish
        working-directory: ./docker/
        run: docker compose exec app \
            -e ACTIONS_ID_TOKEN_REQUEST_URL \
            -e ACTIONS_ID_TOKEN_REQUEST_TOKEN \
            sudo bash -c "cd lib/distopia && sudo npx jsr publish ${{ github.event_name == 'pull_request' && '--dry-run' || '' }}"
