name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  npm:
    name: npmjs.com
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Node Modules Cache
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('bun.lock') }}

      - name: Checkout nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.13'

      - name: Install Deps
        run: bun ci

      - name: Publish
        shell: bash
        run: scripts/npm-publish.sh

  jsr:
    name: jsr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Node Modules Cache
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('bun.lock') }}

      - name: Checkout nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.13'

      - name: Install Deps
        run: bun ci

      - name: Publish
        working-directory: ./lib/distopia
        run: npx jsr publish ${{ github.event_name == 'pull_request' && '--dry-run' || '' }}
