name: Story Book

on:
  pull_request:
  pull_request_target:
  push:
    branches:
      - main
      - release-*

env:
  PUBLIC_URL: http://localhost:3000
  PUBLIC_OWNER_ID: "1261634733037719593"

  PUBLIC_HOME_SERVER_ID: "1505540430110920764"
  PUBLIC_STAFF_ROLE_ID: "1505546268020310117"
  PUBLIC_HONORARY_MEMBER_ROLE_ID: "1505546306721026068"
  PUBLIC_SPECIAL_BOARD_OF_DIRECTORS_ROLE_ID: "1505546372726788126"
  PUBLIC_BOARD_OF_DIRECTORS_ROLE_ID: "1505546412484726804"
  PUBLIC_SUB_BOARD_OF_DIRECTORS_ROLE_ID: "1505546443392422010"

  PUBLIC_BOT_ID: "1505544379639660745"
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  BOT_SECRET: ${{ secrets.BOT_SECRET }}
  BOT_REDIRECT_URL: http://localhost:3000/auth

  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request_target' && github.event.repository.fork) || (github.event_name == 'pull_request' && !github.event.repository.fork)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.15.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install and build
        run: |
          bun install --frozen-lockfile
          npm run build-storybook

      - name: Build
        run: npm run build-storybook
